version: '3.3'
services:
  khokha_entry_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '7500:4000'
    env_file:
      - .env.prod
    networks:
      - one-stop-2021_default

networks:
  one-stop-2021_default:
    external: true
